2020-03-01 02:46:18,061 DEBUG    root            Loaded Command Group: [u'gcloud', u'app']
2020-03-01 02:46:18,113 DEBUG    root            Loaded Command Group: [u'gcloud', u'app', u'deploy']
2020-03-01 02:46:18,117 DEBUG    root            Running [gcloud.app.deploy] with arguments: [DEPLOYABLES:1: "[u'app']"]
2020-03-01 02:46:18,190 DEBUG    root            Loading runtimes experiment config from [gs://runtime-builders/experiments.yaml]
2020-03-01 02:46:18,224 INFO     root            Reading [<googlecloudsdk.api_lib.storage.storage_util.ObjectReference object at 0x7febc0686490>]
2020-03-01 02:46:18,349 DEBUG    root            (gcloud.app.deploy) [/home/justink875/app] does not exist.
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 981, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
    resources = command_instance.Run(args)
  File "/usr/lib/google-cloud-sdk/lib/surface/app/deploy.py", line 110, in Run
    default_strategy=flex_image_build_option_default))
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/app/deploy_util.py", line 575, in RunDeploy
    args.deployables, stager, deployables.GetPathMatchers())
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/app/deployables.py", line 397, in GetDeployables
    raise exceptions.FileNotFoundError(path)
FileNotFoundError: [/home/justink875/app] does not exist.
2020-03-01 02:46:18,350 ERROR    root            (gcloud.app.deploy) [/home/justink875/app] does not exist.
